### PR TITLE
Switched over to using the JS SDK

### PR DESCRIPTION
**Pull request by iangilman**
Currently a work in progress. Still to be done: 
- [x] Build with Gulp

### CODE REVIEW

**Comment by iangilman** [comment]
Ok, I have the Gulp building in. The only thing left is adding keyboard support, but that'll be over in https://github.com/domainr/domainr-search-box.

**Comment by iangilman** [comment]
Here is the PR for keyboard support: https://github.com/domainr/domainr-search-box/pull/9

**Comment by iangilman** [comment]
Now that arrow key support is in the JS API, this should be ready to go (unless there are issues that need to be addressed).

**Comment by case** [comment]
Finally tinkering with this!

The updated UX looks fantastic. But the keyboard shortcuts aren't working for some reason?

I've run `npm install` and `gulp build`, which presumably downloaded the latest version of `domainr-search-box`, which I published ~5 days ago. So it *should* be current.

Any ideas?

**Comment by iangilman** [comment]
@case I just now bumped the required version of the search box module; try `npm install` and `gulp` again. If that doesn't work, blow away your node_modules folder. It worked for me after doing that.

**Comment by case** [comment]
D'oh, of course it was that simple. I'm off my game. :)

**Comment by case** [comment]
:boom: merging.

**Comment by iangilman** [comment]
:+1:

**Pull request merged**
